"use client"

import type React from "react"

import { createContext, useContext, useEffect } from "react"
import { useLocalStorage } from "@/hooks/use-local-storage"

// Define translations
const translations = {
  en: {
    home: "Home",
    categories: "Categories",
    popular: "Popular",
    new: "New",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    profile: "Profile",
    favorites: "Favorites",
    settings: "Settings",
    search: "Search",
    search_placeholder: "Search AI tools, categories, resources...",
    hero_title: "Discover the Best AI Tools",
    hero_subtitle: "Find and explore the most powerful AI tools in one place",
    all: "All",
    chatbots: "Chatbots",
    image_generation: "Image Generation",
    video: "Video",
    audio: "Audio",
    productivity: "Productivity",
    development: "Development",
    business: "Business",
    education: "Education",
    marketing: "Marketing",
    more: "More",
    change_language: "Change Language",
    open_menu: "Open Menu",
    user_menu: "User Menu",
    email: "Email",
    password: "Password",
    forgot_password: "Forgot Password?",
    no_account: "Don't have an account?",
    create_account: "Create Account",
    have_account: "Already have an account?",
    name: "Name",
    confirm_password: "Confirm Password",
    or: "or",
    continue_with_google: "Continue with Google",
    continue_with_github: "Continue with GitHub",
    enter_credentials: "Enter your credentials to login",
    create_account_description: "Create an account to save your favorite AI tools",
    submit: "Submit Tool",
    no_tools_found: "No tools found in this category",
    admin_submissions: "Manage Submissions",
    browse_categories_description: "Browse AI tools by category",
    tool: "tool",
    tools: "tools",
    view: "View",
    most_popular: "Most Popular",
    newest: "Newest",
    popular_description: "Discover the most popular AI tools",
    new_description: "Recently added AI tools",
    visit: "Visit",
    admin_login_hint: "Admin login: admin@admin.com / admin123",
    admin_only: "This page is only accessible to administrators.",
    back_home: "Back to Home",
    bulk_import: "Bulk Import",
    bulk_import_description: "Import multiple AI tools at once using CSV or JSON format.",
    import_tools: "Import AI Tools",
    import_csv_description: "Upload a CSV file with AI tools data.",
    import_json_description: "Upload or paste JSON data with AI tools information.",
    template_format: "Template Format",
    download_template_description: "Download the template to see the required format for importing AI tools.",
    download_template: "Download Template",
    csv_file: "CSV File",
    choose_file: "Choose File",
    json_data: "JSON Data",
    paste_json_here: "Paste JSON data here...",
    upload_json_file: "Upload JSON File",
    import_json: "Import JSON",
    importing: "Importing...",
    import_results: "Import Results",
    total: "Total",
    successful: "Successful",
    failed: "Failed",
    import_errors: "Import Errors",
    success: "Success",
    tools_imported_successfully: "tools were imported successfully.",
    import_csv: "Import CSV",
    invalid_file_type: "Invalid file type",
    please_upload_csv: "Please upload a CSV file",
    please_upload_json: "Please upload a JSON file",
    import_complete: "Import complete",
    tools_imported: "tools imported",
    import_failed: "Import failed",
    no_data: "No data",
    please_enter_json_data: "Please enter JSON data to import",
    back_to_submissions: "Back to Submissions",
  },
  zh: {
    home: "首页",
    categories: "分类",
    popular: "热门",
    new: "新增",
    login: "登录",
    signup: "注册",
    logout: "退出登录",
    profile: "个人资料",
    favorites: "收藏",
    settings: "设置",
    search: "搜索",
    search_placeholder: "搜索AI工具、分类、资源...",
    hero_title: "探索最佳AI工具",
    hero_subtitle: "在AI导航中心中获取最高效的AI工具",
    all: "全部",
    chatbots: "聊天机器人",
    image_generation: "图像生成",
    video: "视频",
    audio: "音频",
    productivity: "生产力",
    development: "开发",
    business: "商业",
    education: "教育",
    marketing: "营销",
    more: "更多",
    change_language: "切换语言",
    open_menu: "打开菜单",
    user_menu: "用户菜单",
    email: "邮箱",
    password: "密码",
    forgot_password: "忘记密码？",
    no_account: "没有账号？",
    create_account: "创建账号",
    have_account: "已有账号？",
    name: "姓名",
    confirm_password: "确认密码",
    or: "或",
    continue_with_google: "使用谷歌账号继续",
    continue_with_github: "使用GitHub账号继续",
    enter_credentials: "输入您的凭据以登录",
    create_account_description: "创建账号以保存您喜欢的AI工具",
    submit: "提交工具",
    no_tools_found: "此分类中没有找到工具",
    admin_submissions: "管理提交",
    browse_categories_description: "按分类浏览AI工具",
    tool: "个工具",
    tools: "个工具",
    view: "查看",
    most_popular: "最受欢迎",
    newest: "最新",
    popular_description: "发现最受欢迎的AI工具",
    new_description: "最近添加的AI工具",
    visit: "访问",
    admin_login_hint: "管理员登录: admin@admin.com / admin123",
    admin_only: "此页面仅管理员可访问。",
    back_home: "返回首页",
    bulk_import: "批量导入",
    bulk_import_description: "使用CSV或JSON格式一次导入多个AI工具。",
    import_tools: "导入AI工具",
    import_csv_description: "上传包含AI工具数据的CSV文件。",
    import_json_description: "上传或粘贴包含AI工具信息的JSON数据。",
    template_format: "模板格式",
    download_template_description: "下载模板以查看导入AI工具所需的格式。",
    download_template: "下载模板",
    csv_file: "CSV文件",
    choose_file: "选择文件",
    json_data: "JSON数据",
    paste_json_here: "在此粘贴JSON数据...",
    upload_json_file: "上传JSON文件",
    import_json: "导入JSON",
    importing: "导入中...",
    import_results: "导入结果",
    total: "总计",
    successful: "成功",
    failed: "失败",
    import_errors: "导入错误",
    success: "成功",
    tools_imported_successfully: "个工具已成功导入。",
    import_csv: "导入CSV",
    invalid_file_type: "无效的文件类型",
    please_upload_csv: "请上传CSV文件",
    please_upload_json: "请上传JSON文件",
    import_complete: "导入完成",
    tools_imported: "个工具已导入",
    import_failed: "导入失败",
    no_data: "没有数据",
    please_enter_json_data: "请输入要导入的JSON数据",
    back_to_submissions: "返回提交管理",
  },
  es: {
    home: "Inicio",
    categories: "Categorías",
    popular: "Popular",
    new: "Nuevo",
    login: "Iniciar Sesión",
    signup: "Registrarse",
    logout: "Cerrar Sesión",
    profile: "Perfil",
    favorites: "Favoritos",
    settings: "Configuración",
    search: "Buscar",
    search_placeholder: "Buscar herramientas de IA, categorías, recursos...",
    hero_title: "Descubre las Mejores Herramientas de IA",
    hero_subtitle: "Encuentra y explora las herramientas de IA más potentes en un solo lugar",
    all: "Todo",
    chatbots: "Chatbots",
    image_generation: "Generación de Imágenes",
    video: "Video",
    audio: "Audio",
    productivity: "Productividad",
    development: "Desarrollo",
    business: "Negocios",
    education: "Educación",
    marketing: "Marketing",
    more: "Más",
    change_language: "Cambiar Idioma",
    open_menu: "Abrir Menú",
    user_menu: "Menú de Usuario",
    email: "Correo Electrónico",
    password: "Contraseña",
    forgot_password: "¿Olvidaste tu Contraseña?",
    no_account: "¿No tienes una cuenta?",
    create_account: "Crear Cuenta",
    have_account: "¿Ya tienes una cuenta?",
    name: "Nombre",
    confirm_password: "Confirmar Contraseña",
    or: "o",
    continue_with_google: "Continuar con Google",
    continue_with_github: "Continuar con GitHub",
    enter_credentials: "Ingresa tus credenciales para iniciar sesión",
    create_account_description: "Crea una cuenta para guardar tus herramientas de IA favoritas",
    submit: "Enviar Herramienta",
    no_tools_found: "No se encontraron herramientas en esta categoría",
    admin_submissions: "Gestionar Envíos",
    browse_categories_description: "Explorar herramientas de IA por categoría",
    tool: "herramienta",
    tools: "herramientas",
    view: "Ver",
    most_popular: "Más Popular",
    newest: "Más Reciente",
    popular_description: "Descubre las herramientas de IA más populares",
    new_description: "Herramientas de IA añadidas recientemente",
    visit: "Visitar",
    admin_login_hint: "Inicio de sesión de administrador: admin@admin.com / admin123",
    admin_only: "Esta página solo es accesible para administradores.",
    back_home: "Volver al Inicio",
    bulk_import: "Importación Masiva",
    bulk_import_description: "Importar múltiples herramientas de IA a la vez usando formato CSV o JSON.",
    import_tools: "Importar Herramientas de IA",
    import_csv_description: "Subir un archivo CSV con datos de herramientas de IA.",
    import_json_description: "Subir o pegar datos JSON con información de herramientas de IA.",
    template_format: "Formato de Plantilla",
    download_template_description:
      "Descarga la plantilla para ver el formato requerido para importar herramientas de IA.",
    download_template: "Descargar Plantilla",
    csv_file: "Archivo CSV",
    choose_file: "Elegir Archivo",
    json_data: "Datos JSON",
    paste_json_here: "Pegar datos JSON aquí...",
    upload_json_file: "Subir Archivo JSON",
    import_json: "Importar JSON",
    importing: "Importando...",
    import_results: "Resultados de Importación",
    total: "Total",
    successful: "Exitosas",
    failed: "Fallidas",
    import_errors: "Errores de Importación",
    success: "Éxito",
    tools_imported_successfully: "herramientas fueron importadas con éxito.",
    import_csv: "Importar CSV",
    invalid_file_type: "Tipo de archivo inválido",
    please_upload_csv: "Por favor sube un archivo CSV",
    please_upload_json: "Por favor sube un archivo JSON",
    import_complete: "Importación completa",
    tools_imported: "herramientas importadas",
    import_failed: "Importación fallida",
    no_data: "Sin datos",
    please_enter_json_data: "Por favor ingresa datos JSON para importar",
    back_to_submissions: "Volver a Envíos",
  },
  fr: {
    home: "Accueil",
    categories: "Catégories",
    popular: "Populaire",
    new: "Nouveau",
    login: "Connexion",
    signup: "S'inscrire",
    logout: "Déconnexion",
    profile: "Profil",
    favorites: "Favoris",
    settings: "Paramètres",
    search: "Rechercher",
    search_placeholder: "Rechercher des outils IA, catégories, ressources...",
    hero_title: "Découvrez les Meilleurs Outils d'IA",
    hero_subtitle: "Trouvez et explorez les outils d'IA les plus puissants en un seul endroit",
    all: "Tous",
    chatbots: "Chatbots",
    image_generation: "Génération d'Images",
    video: "Vidéo",
    audio: "Audio",
    productivity: "Productivité",
    development: "Développement",
    business: "Entreprise",
    education: "Éducation",
    marketing: "Marketing",
    more: "Plus",
    change_language: "Changer de Langue",
    open_menu: "Ouvrir le Menu",
    user_menu: "Menu Utilisateur",
    email: "Email",
    password: "Mot de Passe",
    forgot_password: "Mot de passe oublié ?",
    no_account: "Vous n'avez pas de compte ?",
    create_account: "Créer un Compte",
    have_account: "Vous avez déjà un compte ?",
    name: "Nom",
    confirm_password: "Confirmer le Mot de Passe",
    or: "ou",
    continue_with_google: "Continuer avec Google",
    continue_with_github: "Continuer avec GitHub",
    enter_credentials: "Entrez vos identifiants pour vous connecter",
    create_account_description: "Créez un compte pour sauvegarder vos outils d'IA préférés",
    submit: "Soumettre un Outil",
    no_tools_found: "Aucun outil trouvé dans cette catégorie",
    admin_submissions: "Gérer les Soumissions",
    browse_categories_description: "Parcourir les outils d'IA par catégorie",
    tool: "outil",
    tools: "outils",
    view: "Voir",
    most_popular: "Plus Populaire",
    newest: "Plus Récent",
    popular_description: "Découvrez les outils d'IA les plus populaires",
    new_description: "Outils d'IA récemment ajoutés",
    visit: "Visiter",
    admin_login_hint: "Connexion administrateur: admin@admin.com / admin123",
    admin_only: "Cette page n'est accessible qu'aux administrateurs.",
    back_home: "Retour à l'Accueil",
    bulk_import: "Importation en Masse",
    bulk_import_description: "Importez plusieurs outils d'IA à la fois en utilisant le format CSV ou JSON.",
    import_tools: "Importer des Outils d'IA",
    import_csv_description: "Téléchargez un fichier CSV avec les données des outils d'IA.",
    import_json_description: "Téléchargez ou collez des données JSON avec des informations sur les outils d'IA.",
    template_format: "Format du Modèle",
    download_template_description: "Téléchargez le modèle pour voir le format requis pour importer des outils d'IA.",
    download_template: "Télécharger le Modèle",
    csv_file: "Fichier CSV",
    choose_file: "Choisir un Fichier",
    json_data: "Données JSON",
    paste_json_here: "Collez les données JSON ici...",
    upload_json_file: "Télécharger un Fichier JSON",
    import_json: "Importer JSON",
    importing: "Importation en cours...",
    import_results: "Résultats de l'Importation",
    total: "Total",
    successful: "Réussis",
    failed: "Échoués",
    import_errors: "Erreurs d'Importation",
    success: "Succès",
    tools_imported_successfully: "outils ont été importés avec succès.",
    import_csv: "Importer CSV",
    invalid_file_type: "Type de fichier invalide",
    please_upload_csv: "Veuillez télécharger un fichier CSV",
    please_upload_json: "Veuillez télécharger un fichier JSON",
    import_complete: "Importation terminée",
    tools_imported: "outils importés",
    import_failed: "Échec de l'importation",
    no_data: "Aucune donnée",
    please_enter_json_data: "Veuillez saisir des données JSON à importer",
    back_to_submissions: "Retour aux Soumissions",
  },
  ja: {
    home: "ホーム",
    categories: "カテゴリー",
    popular: "人気",
    new: "新着",
    login: "ログイン",
    signup: "登録",
    logout: "ログアウト",
    profile: "プロフィール",
    favorites: "お気に入り",
    settings: "設定",
    search: "検索",
    search_placeholder: "AIツール、カテゴリー、リソースを検索...",
    hero_title: "最高のAIツールを発見",
    hero_subtitle: "最も強力なAIツールを一か所で見つけて探索",
    all: "すべて",
    chatbots: "チャットボット",
    image_generation: "画像生成",
    video: "ビデオ",
    audio: "オーディオ",
    productivity: "生産性",
    development: "開発",
    business: "ビジネス",
    education: "教育",
    marketing: "マーケティング",
    more: "もっと見る",
    change_language: "言語を変更",
    open_menu: "メニューを開く",
    user_menu: "ユーザーメニュー",
    email: "メールアドレス",
    password: "パスワード",
    forgot_password: "パスワードをお忘れですか？",
    no_account: "アカウントをお持ちでないですか？",
    create_account: "アカウント作成",
    have_account: "すでにアカウントをお持ちですか？",
    name: "名前",
    confirm_password: "パスワード確認",
    or: "または",
    continue_with_google: "Googleで続ける",
    continue_with_github: "GitHubで続ける",
    enter_credentials: "ログインするには認証情報を入力してください",
    create_account_description: "お気に入りのAIツールを保存するためのアカウントを作成",
    submit: "ツールを提出",
    no_tools_found: "このカテゴリにツールが見つかりません",
    admin_submissions: "提出物を管理",
    browse_categories_description: "カテゴリ別にAIツールを閲覧",
    tool: "ツール",
    tools: "ツール",
    view: "表示",
    most_popular: "最も人気",
    newest: "最新",
    popular_description: "最も人気のあるAIツールを発見",
    new_description: "最近追加されたAIツール",
    visit: "訪問",
    admin_login_hint: "管理者ログイン: admin@admin.com / admin123",
    admin_only: "このページは管理者のみがアクセスできます。",
    back_home: "ホームに戻る",
    bulk_import: "一括インポート",
    bulk_import_description: "CSVまたはJSON形式を使用して複数のAIツールを一度にインポートします。",
    import_tools: "AIツールをインポート",
    import_csv_description: "AIツールデータを含むCSVファイルをアップロードします。",
    import_json_description: "AIツール情報を含むJSONデータをアップロードまたは貼り付けます。",
    template_format: "テンプレート形式",
    download_template_description:
      "AIツールをインポートするために必要な形式を確認するためにテンプレートをダウンロードしてください。",
    download_template: "テンプレートをダウンロード",
    csv_file: "CSVファイル",
    choose_file: "ファイルを選択",
    json_data: "JSONデータ",
    paste_json_here: "ここにJSONデータを貼り付けてください...",
    upload_json_file: "JSONファイルをアップロード",
    import_json: "JSONをインポート",
    importing: "インポート中...",
    import_results: "インポート結果",
    total: "合計",
    successful: "成功",
    failed: "失敗",
    import_errors: "インポートエラー",
    success: "成功",
    tools_imported_successfully: "ツールが正常にインポートされました。",
    import_csv: "CSVをインポート",
    invalid_file_type: "無効なファイルタイプ",
    please_upload_csv: "CSVファイルをアップロードしてください",
    please_upload_json: "JSONファイルをアップロードしてください",
    import_complete: "インポート完了",
    tools_imported: "ツールがインポートされました",
    import_failed: "インポート失敗",
    no_data: "データなし",
    please_enter_json_data: "インポートするJSONデータを入力してください",
    back_to_submissions: "提出管理に戻る",
  },
  de: {
    home: "Startseite",
    categories: "Kategorien",
    popular: "Beliebt",
    new: "Neu",
    login: "Anmelden",
    signup: "Registrieren",
    logout: "Abmelden",
    profile: "Profil",
    favorites: "Favoriten",
    settings: "Einstellungen",
    search: "Suchen",
    search_placeholder: "KI-Tools, Kategorien, Ressourcen suchen...",
    hero_title: "Entdecke die besten KI-Tools",
    hero_subtitle: "Finde und erkunde die leistungsstärksten KI-Tools an einem Ort",
    all: "Alle",
    chatbots: "Chatbots",
    image_generation: "Bilderzeugung",
    video: "Video",
    audio: "Audio",
    productivity: "Produktivität",
    development: "Entwicklung",
    business: "Geschäft",
    education: "Bildung",
    marketing: "Marketing",
    more: "Mehr",
    change_language: "Sprache ändern",
    open_menu: "Menü öffnen",
    user_menu: "Benutzermenü",
    email: "E-Mail",
    password: "Passwort",
    forgot_password: "Passwort vergessen?",
    no_account: "Noch kein Konto?",
    create_account: "Konto erstellen",
    have_account: "Bereits ein Konto?",
    name: "Name",
    confirm_password: "Passwort bestätigen",
    or: "oder",
    continue_with_google: "Mit Google fortfahren",
    continue_with_github: "Mit GitHub fortfahren",
    enter_credentials: "Geben Sie Ihre Anmeldedaten ein",
    create_account_description: "Erstellen Sie ein Konto, um Ihre Lieblings-KI-Tools zu speichern",
    submit: "Tool einreichen",
    no_tools_found: "Keine Tools in dieser Kategorie gefunden",
    admin_submissions: "Einreichungen verwalten",
    browse_categories_description: "KI-Tools nach Kategorie durchsuchen",
    tool: "Tool",
    tools: "Tools",
    view: "Ansehen",
    most_popular: "Beliebteste",
    newest: "Neueste",
    popular_description: "Entdecke die beliebtesten KI-Tools",
    new_description: "Kürzlich hinzugefügte KI-Tools",
    visit: "Besuchen",
    admin_login_hint: "Admin-Login: admin@admin.com / admin123",
    admin_only: "Diese Seite ist nur für Administratoren zugänglich.",
    back_home: "Zurück zur Startseite",
    bulk_import: "Massenimport",
    bulk_import_description: "Importieren Sie mehrere KI-Tools auf einmal im CSV- oder JSON-Format.",
    import_tools: "KI-Tools importieren",
    import_csv_description: "Laden Sie eine CSV-Datei mit KI-Tool-Daten hoch.",
    import_json_description: "Laden Sie JSON-Daten mit KI-Tool-Informationen hoch oder fügen Sie sie ein.",
    template_format: "Vorlagenformat",
    download_template_description:
      "Laden Sie die Vorlage herunter, um das erforderliche Format für den Import von KI-Tools zu sehen.",
    download_template: "Vorlage herunterladen",
    csv_file: "CSV-Datei",
    choose_file: "Datei auswählen",
    json_data: "JSON-Daten",
    paste_json_here: "JSON-Daten hier einfügen...",
    upload_json_file: "JSON-Datei hochladen",
    import_json: "JSON importieren",
    importing: "Importieren...",
    import_results: "Importergebnisse",
    total: "Gesamt",
    successful: "Erfolgreich",
    failed: "Fehlgeschlagen",
    import_errors: "Importfehler",
    success: "Erfolg",
    tools_imported_successfully: "Tools wurden erfolgreich importiert.",
    import_csv: "CSV importieren",
    invalid_file_type: "Ungültiger Dateityp",
    please_upload_csv: "Bitte laden Sie eine CSV-Datei hoch",
    please_upload_json: "Bitte laden Sie eine JSON-Datei hoch",
    import_complete: "Import abgeschlossen",
    tools_imported: "Tools importiert",
    import_failed: "Import fehlgeschlagen",
    no_data: "Keine Daten",
    please_enter_json_data: "Bitte geben Sie JSON-Daten zum Importieren ein",
    back_to_submissions: "Zurück zu Einreichungen",
  },
}

type LanguageContextType = {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({
  children,
}: {
  children: React.ReactNode
}) {
  // Make sure English is the default language
  const [language, setLanguageState] = useLocalStorage<string>(
    "language",
    "en", // Default to English
  )

  const setLanguage = (lang: string) => {
    setLanguageState(lang)
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof (typeof translations)["en"]] || key
  }

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

